### ISSUE TITLE
Issues setting up the deleteAMI function

### ISSUE THREAD

**Issue by cpeter56** [webdigi/AWS-AMI-Automated-Creation-Deletion#2]
I've got the createAMI to work but I was wondering what kind of tags you're using to set up the deleteAMI function.

**Comment by webdigi** [comment]
Every AMI just has a DeleteBackupsAutoOn tag set to yes. This is to identify tags that need to be deleted. There are no other tags setup to mark deleteAMI.

Also look at the AMI name ending with a number sequence 1490753537232 which is linux epoch to mark deletion time.

**Comment by cpeter56** [comment]
After looking at it further this explains everything. Thank you for posting such a detailed guide and being on top of assisting others through the process!
