### ISSUE TITLE
No AMI created (snapshots are created)

### ISSUE THREAD

**Issue by huschlen** [webdigi/AWS-AMI-Automated-Creation-Deletion#9]
I have automated AMI creation that runs everyday at 12:00 am.  It created associated snapshots, but I am not able to find AMI that should have been created.

**Comment by huschlen** [comment]
Actually, I stand corrected.  No snapshots are created either.  When I test this lambda, I get this note.

"The area below shows the result returned by your function execution. Learn more about returning results from your function."
null

I have this lambda function in the same region and have set up tags, roles and timeout correctly.

**Comment by huschlen** [comment]
Sorry, I was not setting the correct region.

**Comment by webdigi** [comment]
Thanks for your comment.
